#!/bin/sh

dir=$(readlink $0)

if [ x$dir == x ] ; then
	dir=$(cd $(dirname "$1") && pwd -P)
else
	#startswith
	if [[ $dir != /* ]] ; then
		dir=$(cd $(dirname "$1") && pwd -P)/$dir
	fi
	dir=$(dirname $dir)
fi

if [ x$1 == x ] ; then
	echo 'rssh {alias|ls|add|rm|edit|put|get|exec|call}'
elif [ $1 == 'install' ] ; then
	ln -s $dir/rssh /usr/local/bin/rssh
elif [ $1 == 'ls' ] || [ $1 == 'add' ] || [ $1 == 'rm' ] || [ $1 == 'edit' ]  || [ $1 == 'get' ]  || [ $1 == 'put' ]  || [ $1 == 'call' ]  || [ $1 == 'exec' ] ; then
	python $dir/rssh.py "$@"
else
	expect $dir/rssh.ex "$@"
fi
