#!/bin/sh

dir=$(readlink $0)

if [ x$dir == x ] ; then
	dir=$(cd $(dirname "$1") && pwd -P)
else
	#startswith
	if [[ $dir != /* ]] ; then
		dir=$(cd $(dirname "$1") && pwd -P)/$dir
	fi
	dir=$(dirname $dir)
fi

if [ $(python $dir/rssh.py test $1) == 'OK' ] ; then
	python $dir/rssh.py "$@"
else
	expect $dir/rssh.ex "$@"
fi
