#!/bin/sh

dir=$(readlink $0)

if [ x$dir == x ] ; then
	dir=$(cd $(dirname "$1") && pwd -P)
else
	#startswith
	if [[ $dir != /* ]] ; then
		dir=$(cd $(dirname "$1") && pwd -P)/$dir
	fi
	dir=$(dirname $dir)
fi

if [ ! -z $1 ] && [ $1 == 'install' ] ; then
	ln -s $dir/rssh /usr/local/bin/rssh
#elif [ $(python $dir/rssh.py test $1) != 'OK' ] ; then
#	expect $dir/rssh.ex "$@"
else
	python $dir/rssh.py "$@"
fi
